# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Dotai < Formula
  desc "AI coding environment setup wizard, one shot"
  homepage "https://github.com/TomyQB/dotai"
  version "0.3.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/TomyQB/dotai/releases/download/v0.3.1/dotai_0.3.1_darwin_amd64.tar.gz"
      sha256 "bfe73584a111e294b1a9159a3f86a3da2bff4ac6ae6130f22122a97334874c7a"

      define_method(:install) do
        bin.install "dotai"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/TomyQB/dotai/releases/download/v0.3.1/dotai_0.3.1_darwin_arm64.tar.gz"
      sha256 "4c3aff4851770c564011bed70eb172facd3300f0dd907c39d629d6d1a2c74fb7"

      define_method(:install) do
        bin.install "dotai"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/TomyQB/dotai/releases/download/v0.3.1/dotai_0.3.1_linux_amd64.tar.gz"
      sha256 "15a525564e75c0adb2a8201ccb38a701755b6ea4eaecfede6d2a3043b428d107"
      define_method(:install) do
        bin.install "dotai"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/TomyQB/dotai/releases/download/v0.3.1/dotai_0.3.1_linux_arm64.tar.gz"
      sha256 "3b9d0ceb501ac41a25f5d4806b3e6ec119bd7931d849233750dfd396097fdaec"
      define_method(:install) do
        bin.install "dotai"
      end
    end
  end

  test do
    system "#{bin}/dotai", "version"
  end
end
