# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Dotai < Formula
  desc "AI coding environment setup wizard, one shot"
  homepage "https://github.com/TomyQB/dotai"
  version "0.3.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/TomyQB/dotai/releases/download/v0.3.2/dotai_0.3.2_darwin_amd64.tar.gz"
      sha256 "f6039dcb4f2d760f8106833930fa4bd1ca06d1d6ce9ef3d670f0c2cd93b18722"

      define_method(:install) do
        bin.install "dotai"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/TomyQB/dotai/releases/download/v0.3.2/dotai_0.3.2_darwin_arm64.tar.gz"
      sha256 "551536e9e51f183d5514def3c94f2e1cbb669c599db0d11493312107e2b96951"

      define_method(:install) do
        bin.install "dotai"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/TomyQB/dotai/releases/download/v0.3.2/dotai_0.3.2_linux_amd64.tar.gz"
      sha256 "81be447bcc94cb65b713ac899ae69ecb3d04b3d97a15e48c8ca01d3b0bf62991"
      define_method(:install) do
        bin.install "dotai"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/TomyQB/dotai/releases/download/v0.3.2/dotai_0.3.2_linux_arm64.tar.gz"
      sha256 "aa75f554414a96536389f066008e9d89987b73a68eb2bb02fd025d8d741e4e99"
      define_method(:install) do
        bin.install "dotai"
      end
    end
  end

  test do
    system "#{bin}/dotai", "version"
  end
end
