# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Dotai < Formula
  desc "AI coding environment setup wizard, one shot"
  homepage "https://github.com/TomyQB/dotai"
  version "0.3.10"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/TomyQB/dotai/releases/download/v0.3.10/dotai_0.3.10_darwin_amd64.tar.gz"
      sha256 "99a85c8d53802d5fc42b5f035602c4918e8dd4f125486daf4abc1c37b09f8d4d"

      define_method(:install) do
        bin.install "dotai"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/TomyQB/dotai/releases/download/v0.3.10/dotai_0.3.10_darwin_arm64.tar.gz"
      sha256 "aa8202c2c2d95032f2e20306ba652e4b4f5e61f3892918f5e6dc8485b5c8d65f"

      define_method(:install) do
        bin.install "dotai"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/TomyQB/dotai/releases/download/v0.3.10/dotai_0.3.10_linux_amd64.tar.gz"
      sha256 "3a84c27b3f95de9b666978f2c09772c74b9298f26be3a225da6d723e51935062"
      define_method(:install) do
        bin.install "dotai"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/TomyQB/dotai/releases/download/v0.3.10/dotai_0.3.10_linux_arm64.tar.gz"
      sha256 "52895b43d28c1b77273095606300005e7041bc3b8a70415556563e5f048f0358"
      define_method(:install) do
        bin.install "dotai"
      end
    end
  end

  test do
    system "#{bin}/dotai", "version"
  end
end
