# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class MemCli < Formula
  desc "Living agent-facing documentation for your projects, enforced by hooks"
  homepage "https://github.com/TomyQB/mem-cli"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/TomyQB/mem-cli/releases/download/v0.1.0/mem-cli_0.1.0_darwin_amd64.tar.gz"
      sha256 "4fb05776893e7dab0a00a1473b8226c8f793ac1d4d4f578880eb50e3fa371fb2"

      define_method(:install) do
        bin.install "memcli"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/TomyQB/mem-cli/releases/download/v0.1.0/mem-cli_0.1.0_darwin_arm64.tar.gz"
      sha256 "0f7373cea3f090924e161c6c0de5a2ae227eeaf89b73ec1aca3d66302b713bff"

      define_method(:install) do
        bin.install "memcli"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/TomyQB/mem-cli/releases/download/v0.1.0/mem-cli_0.1.0_linux_amd64.tar.gz"
      sha256 "ca4d0c81644bb47ffb8860e74e1c3289bd0fbedcdabf423ba77c02dbf8396a30"
      define_method(:install) do
        bin.install "memcli"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/TomyQB/mem-cli/releases/download/v0.1.0/mem-cli_0.1.0_linux_arm64.tar.gz"
      sha256 "98614b3624760af0f666d45b43023c524b1c49999ebad6b27884960d899f9bd9"
      define_method(:install) do
        bin.install "memcli"
      end
    end
  end

  test do
    system "#{bin}/memcli", "version"
  end
end
