# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Memcli < Formula
  desc "Read-only browser for .agent-memory/ project trees"
  homepage "https://github.com/TomyQB/dotai"
  version "0.3.8"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/TomyQB/dotai/releases/download/v0.3.8/memcli_0.3.8_darwin_amd64.tar.gz"
      sha256 "430aef1baa31b4916c3f5627dfd9bcd5b1ae0fd62d73d0201c403dd76353c5ed"

      define_method(:install) do
        bin.install "memcli"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/TomyQB/dotai/releases/download/v0.3.8/memcli_0.3.8_darwin_arm64.tar.gz"
      sha256 "2c7b0a171347b62d33b2152b930cd8014604dc54a481167c0f0d90e6fbaceca4"

      define_method(:install) do
        bin.install "memcli"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/TomyQB/dotai/releases/download/v0.3.8/memcli_0.3.8_linux_amd64.tar.gz"
      sha256 "c11f236535e64f3d0fcfd7522fc1401f0666d1b4d9b6fe7c082e78ac9a022f56"
      define_method(:install) do
        bin.install "memcli"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/TomyQB/dotai/releases/download/v0.3.8/memcli_0.3.8_linux_arm64.tar.gz"
      sha256 "3e761f74a2f34289f63db085d3dfabf9bc5755e09067ee669f1c67d680b15199"
      define_method(:install) do
        bin.install "memcli"
      end
    end
  end

  test do
    system "#{bin}/memcli", "version"
  end
end
