# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Memcli < Formula
  desc "Read-only browser for .agent-memory/ project trees"
  homepage "https://github.com/TomyQB/dotai"
  version "0.3.5"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/TomyQB/dotai/releases/download/v0.3.5/memcli_0.3.5_darwin_amd64.tar.gz"
      sha256 "526bbf91c94f791f920f3876d46bb769753f5da99a32cddbb96c6d26f2cdcaef"

      define_method(:install) do
        bin.install "memcli"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/TomyQB/dotai/releases/download/v0.3.5/memcli_0.3.5_darwin_arm64.tar.gz"
      sha256 "02b282a609465b5f1fb7f9655d0d3f40d0fa3cae709ce1fe5db6ac134e4cd1a7"

      define_method(:install) do
        bin.install "memcli"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/TomyQB/dotai/releases/download/v0.3.5/memcli_0.3.5_linux_amd64.tar.gz"
      sha256 "fbd428de35cbef33372e29a5fc866f229a93a30ff1c7fdda79972baf4382ae19"
      define_method(:install) do
        bin.install "memcli"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/TomyQB/dotai/releases/download/v0.3.5/memcli_0.3.5_linux_arm64.tar.gz"
      sha256 "ceea2579d9fb84ece2b0c7270ae9c50c4b23a7d8281c128f7abfa9fa66e6cd6e"
      define_method(:install) do
        bin.install "memcli"
      end
    end
  end

  test do
    system "#{bin}/memcli", "version"
  end
end
