# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Memcli < Formula
  desc "Read-only browser for .agent-memory/ project trees"
  homepage "https://github.com/TomyQB/dotai"
  version "0.3.4"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/TomyQB/dotai/releases/download/v0.3.4/memcli_0.3.4_darwin_amd64.tar.gz"
      sha256 "551a459cbd9ce2644efd171e06a6176678f960031431cb16d66e9950b9e08405"

      define_method(:install) do
        bin.install "memcli"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/TomyQB/dotai/releases/download/v0.3.4/memcli_0.3.4_darwin_arm64.tar.gz"
      sha256 "17b3766e1f5b2cd1abf8de40d548db6a5c458aec46f435e9c67e0d578413558e"

      define_method(:install) do
        bin.install "memcli"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/TomyQB/dotai/releases/download/v0.3.4/memcli_0.3.4_linux_amd64.tar.gz"
      sha256 "1afd6a2c8875e89f4d9090710e2db1d6637f2be36db171d377fe754d8cd9c57e"
      define_method(:install) do
        bin.install "memcli"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/TomyQB/dotai/releases/download/v0.3.4/memcli_0.3.4_linux_arm64.tar.gz"
      sha256 "3bc27b1d9377b6ace8cb30ea5ad49037d0ebbff0be5a3091b1567ef2f14a8d39"
      define_method(:install) do
        bin.install "memcli"
      end
    end
  end

  test do
    system "#{bin}/memcli", "version"
  end
end
